graph TD
    N0(["Inicio"])
    N1["var edad = 18"]
    N2{"si (edad &gt;= 18)"}
    N3["escribir(&quot;Sos mayor de edad&quot;)"]
    N2 -- Si --> N3
    N4((" "))
    N3 --> N4
    N5["escribir(&quot;Sos menor de edad&quot;)"]
    N2 -- Sino --> N5
    N5 --> N4
    N1 --> N2
    N6["var nota = 85"]
    N4 --> N6
    N7{"si (nota &gt;= 90)"}
    N8["escribir(&quot;Excelente!&quot;)"]
    N7 -- Si --> N8
    N9((" "))
    N8 --> N9
    N10{"si (nota &gt;= 70)"}
    N11["escribir(&quot;Buen trabajo!&quot;)"]
    N10 -- Si --> N11
    N12((" "))
    N11 --> N12
    N13["escribir(&quot;Seguí estudiando!&quot;)"]
    N10 -- Sino --> N13
    N13 --> N12
    N7 -- Sino --> N10
    N12 --> N9
    N6 --> N7
    N0 --> N1
    N14(["Fin"])
    N9 --> N14
